/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "cqhjtoayphybgwmbnfqt"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxaGp0b2F5cGh5Ymd3bWJuZnF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc1MDE4OTEsImV4cCI6MjA4MzA3Nzg5MX0.GgDusj2tnJg6FWo7_-HXtd8m-6FDX02kCITkclaqLBE"